### ISSUE TITLE
Updated permissions are not reconciled

### ISSUE THREAD

**Issue by cuppett** [cuppett/mysql-dba-operator#27]
When changing the list of permissions in:

```yaml
spec:
  databasePermissions:
    - databaseName: manage
      grants:
        - SELECT
        - INSERT
        - UPDATE
        - DROP
        - REFERENCES
        - INDEX
        - ALTER
        - CREATE VIEW
        - LOCK TABLES
```

No updates are made to the user entry. Need to compare spec/status to sort that out.
